In [2]:
import torch
import numpy as np
import time

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


CPU vs GPU comparison

In [4]:
%%time
start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00099468
CPU times: total: 0 ns
Wall time: 995 µs


In [5]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.12948799
0.12237048


In [6]:
# embeddings, torch.stack, torch.multinomial, torch.tril, torch.triu, input.T / input.transpose, nn.Linear, torch.cat, F.softmax (show all the examples of functions/methods with pytorch docs)


# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [7]:
# concatinate tensors
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [8]:
# triangle lower

out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [9]:
# triangle upper

out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [10]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [11]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [12]:
input = torch.zeros(2, 3, 4)
out1 = input.transpose(0, 2)
out2 = input.transpose(-3,-1)
print(out1.shape)
print(out2.shape)
# torch.permute works the same but you provide the new order of dimensions instead of the dimensions you'd like to swap.

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])


In [13]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3, tensor1])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 2, 3]])

In [14]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ 3.2300, -1.1305, -6.5120], grad_fn=<SqueezeBackward4>)


In [15]:
import torch.nn.functional as F

# Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax using torch.nn.functional.softmax()
# softmax(x_1) = e^x_1 / sum(e^x_i)
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [16]:
# Initialize an embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[ 1.5994, -0.7365, -0.6860,  1.2805,  1.4239, -0.4589],
        [ 0.1494,  1.2365,  1.5396, -0.1528, -0.8955, -0.6379],
        [ 1.3743, -0.9197,  1.7485,  0.7579,  0.5162, -0.1018],
        [ 1.2610,  0.6676, -0.1840,  0.1241,  1.2713, -1.9596]],
       grad_fn=<EmbeddingBackward0>)


In [17]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
# print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [18]:
int_64 = torch.randint(1, (3, 2)).float()
#type int64
float_32 = torch.rand(2,3)
#type float32
print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

torch.float32 torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [19]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x,y,z)
# print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


In [22]:
input = torch.rand((4, 8, 10))
B, T, C = input.shape
output = input.view(B*T, C)
print(output)
# print(input)
# print(output[:, -1, :])

tensor([[0.8001, 0.0188, 0.3444, 0.6475, 0.1464, 0.6117, 0.3986, 0.1711, 0.1297,
         0.7951],
        [0.9463, 0.4268, 0.7270, 0.1815, 0.7021, 0.9100, 0.3555, 0.6487, 0.6486,
         0.6391],
        [0.1031, 0.7263, 0.8835, 0.7530, 0.6693, 0.0303, 0.5966, 0.8514, 0.7966,
         0.9217],
        [0.6800, 0.6959, 0.8172, 0.8997, 0.1913, 0.9419, 0.6902, 0.8517, 0.9033,
         0.0441],
        [0.0297, 0.1139, 0.7615, 0.8667, 0.3961, 0.0669, 0.4588, 0.1337, 0.8272,
         0.5576],
        [0.6951, 0.5094, 0.8077, 0.6247, 0.9030, 0.3781, 0.1282, 0.0335, 0.9548,
         0.5697],
        [0.7806, 0.4590, 0.2975, 0.0311, 0.2345, 0.9535, 0.4786, 0.5881, 0.1651,
         0.3301],
        [0.5598, 0.3371, 0.3664, 0.8623, 0.2690, 0.7993, 0.1705, 0.4508, 0.2471,
         0.5826],
        [0.6917, 0.2765, 0.4522, 0.1527, 0.7095, 0.7500, 0.0946, 0.0292, 0.7727,
         0.7362],
        [0.0506, 0.6171, 0.3091, 0.0395, 0.4728, 0.2270, 0.3349, 0.9833, 0.1714,
         0.0572],
        [0

Examples

In [ ]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-44, -90, -55,  -4,  66, -86])

In [ ]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [ ]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
arange = torch.arange(15,30)
arange

tensor([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
linspace = torch.linspace(3, 10, steps = 5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [ ]:
logspace = torch.logspace(start = -10, end=10, steps = 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [ ]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[6551511435120,             0,             0],
        [            0,             0,             0]])